### ISSUE TITLE
invalid middleware "my-plugin@file" configuration: invalid middleware type or middleware does not exist

### ISSUE THREAD

**Issue by dusty-cjh** [dusty-cjh/loginAuth#1]
## Objective 
Launch a simple plugin demo
## Work Env
Traefik with docker, 
My PC MacM1 Golang1.20 installed.
My plugin source code(which was created from this template and I haven't add anything) is in the path:
`/Users/jiahao.chen/go/src/github.com/dusty-cjh/loginAuth`

### Traefik Static Config:
```yaml
... ignore others ...
experimental:
  hub: true
  localPlugins:
    example:
      moduleName: github.com/traefik/plugindemo
```

### Traefik Dynamic Config:
```yaml
    whoami:
      entryPoints:
        - websecure
      service: whoami-traefik@docker
      tls: {}
      rule: "Host(`whoami.localhost`)"
      middlewares:
        - my-plugin

... ignore unnecessary...
  middlewares:
    my-plugin:
      plugin:
        example:
          headers:
            Foo: Bar
```

## Problem
The Traefik panel reported this:
```
invalid middleware "my-plugin@file" configuration: invalid middleware type or middleware does not exist
```
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/45847340/223999813-a2b3ba6e-0f29-4834-b029-8f21955e3fb5.png">

## Questions
1. Whether any step wrong with the configuration?
2. Where can I find more latest Treafik Plugin tutorials? 
3. I'm building wechat middleware for user authentication, any other solution I can choose?

Thanks for your help, I wish Traefik will be better!
